linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - goerr113
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - rowserrcheck
    - stylecheck
    - testpackage
    - unparam
    - vet
    - wsl
