linters:
  enable:
    - goerr113
    - errcheck
    - errorlint
    - asciicheck
    - ineffassign
    - gofmt
    - goimports
    - gofumpt
    - goconst
    - gocritic
    - bodyclose
    - gosimple
    - noctx
    - unparam
    - goprintffuncname
    - unused
    - unconvert
    - vet
    - nakedret
    - exportloopref
    - misspell
    # https://github.com/golangci/golangci-lint/issues/2649
    # - rowserrcheck
    - testpackage
    - govet
    - stylecheck
    - wsl
    - nilerr
    - revive
    - prealloc
  disable:
    - gocognit
    - gocyclo
    - godot
    - gomnd
    - gosec
linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude: errcheck-excludes.txt
  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
        severity: warning
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: package-comments
      # - name: add-constant
      #   severity: warning
      #   arguments:
      #     - maxLitCount: "3"
      #       allowStrs: '""'
      #       allowInts: "0,1,2"
      #       allowFloats: "0.0,0.,1.0,1.,2.0,2."
  issues:
    fix: true
run:
  skip-files:
    - echokit/echoapmkit/echoapmkit_recover_middleware.go
