version: '3'
services:
  googlecloud-pubsub:
    image: google/cloud-sdk:335.0.0
    entrypoint: gcloud --quiet beta emulators pubsub start --host-port=googlecloud-pubsub:8085 --verbosity=debug --log-http
    restart: unless-stopped
    ports:
      - 8085:8085

  spring-config-server:
    image: hyness/spring-cloud-config-server:3.0.3
    volumes:
      - ${PWD}/examples/springcloud-config/data:/config
    ports:
      - 8888:8888
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - ENCRYPT_KEY=supersecret2021

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ${PWD}/es-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  es-apm-server:
    image: docker.elastic.co/apm/apm-server:7.12.0
    depends_on:
      - elasticsearch
      - kibana
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
    - 8200:8200
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=kibana:5601
         -E output.elasticsearch.hosts=["elasticsearch:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
