version: '3'
services:
  googlecloud-pubsub:
    image: google/cloud-sdk:228.0.0
    entrypoint: gcloud --quiet beta emulators pubsub start --host-port=googlecloud-pubsub:8085 --verbosity=debug --log-http
    restart: unless-stopped
    ports:
      - 8085:8085

  spring-config-server:
    image: hyness/spring-cloud-config-server:3.0.3
    volumes:
      - ${PWD}/example/springcloud-config/data:/config
    ports:
      - 8888:8888
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - ENCRYPT_KEY=supersecret2021
