version: '3'
services:
  googlecloud-pubsub:
    image: google/cloud-sdk:228.0.0
    entrypoint: gcloud --quiet beta emulators pubsub start --host-port=googlecloud-pubsub:8085 --verbosity=debug --log-http
    restart: unless-stopped
    ports:
      - 8085:8085
