// Package config provides abstraction for key-value runtime store
package config

import (
	"time"
)

// KVStore abstracts static-typed values reader from kv-store.
type KVStore interface {
	// IsSet ...
	IsSet(key string) bool
	// Get ...
	Get(key string) interface{}
	// AllKeys ...
	AllKeys() []string
	// GetBool ...
	GetBool(key string) bool
	// GetTime ...
	GetTime(key string) time.Time
	// GetDuration ...
	GetDuration(key string) time.Duration
	// GetInt ...
	GetInt(key string) int
	// GetInt32 ...
	GetInt32(key string) int32
	// GetInt64 ...
	GetInt64(key string) int64
	// GetIntSlice ...
	GetIntSlice(key string) []int
	// GetString ...
	GetString(key string) string
	// GetStringSlice ...
	GetStringSlice(key string) []string
	// GetStringMap ...
	GetStringMap(key string) map[string]interface{}
	// GetStringMapStringSlice ...
	GetStringMapStringSlice(key string) map[string][]string
	// GetFloat64 ...
	GetFloat64(key string) float64
	// GetUint ...
	GetUint(key string) uint
	// GetUint32 ...
	GetUint32(key string) uint32
	// GetUint64 ...
	GetUint64(key string) uint64
	// GetSizeInBytes ...
	GetSizeInBytes(key string) uint
}
